CODEMAP = {
    "source": {
        "file": "JEE Mains 2022.xlsx",
        "sheet": "Full Data",
        "header": 0,
    },
    "constants": {
        "test_year": "2022",
        "test_name": "JEE",
        "mains_max_score": 300,
    },
    "columns": {
        "application_no":           ["APPNO"],
        "student_full_name":        ["CNAME", "Student Name"],
        "dob":                      ["DOB"],
        "student_gender":           ["GENDER"],
        "_pwd_raw":                 ["PWD"],
        "category":                 ["CAT"],
        "school_code":              ["SCODE_E"],
        "roll_no_s1":               ["rollno", "ROLLNO"],
        # 2022 has explicit JNV columns
        "student_state":            ["JNV State", "StateName", "State"],
        "district_12":              ["JNV District", "districtName", "District"],
        "place_of_school":          ["PlaceofSchooling", "PlaceofSchool"],
        "jnv_name":                 ["DB JNV Name", "JNV Name"],
        "jnv_region":               ["DB JNV Region"],
        "year_of_passing_12":       ["yearOfPassing"],
        "board_12":                 ["boardName", "Board"],
        "marks_12_obtained":        ["obtainedMark"],
        "marks_12_total":           ["totalMark"],
        "marks_12_pct":             ["percentageOfMarks"],
        "mains_appeared_for_exam":        ["PS_TOT_P1F"],
        "mains_physics_score":            ["PS_PHY_P1F"],
        "mains_chemistry_score":          ["PS_CHE_P1F"],
        "mains_maths_score":              ["PS_MAT_P1F"],
        "mains_total_score":              ["PS_TOT_P1F"],
        "mains_all_india_rank":           ["All India Rank", "AI_CRL1"],
        "mains_all_india_pwd_rank":       ["AI_CRL1PH"],
        "mains_obc_rank":                 ["AI_OBC1"],
        "mains_sc_rank":                  ["AI_SC1"],
        "mains_st_rank":                  ["AI_ST1"],
        "mains_ews_rank":                 ["AI_EWS1"],
        "jee_mains_qualified":      ["Qualified"],
        # NELIG_ADV: True = ineligible for JEE Advanced
        "jee_adv_ineligible":       ["NELIG_ADV"],
        "jee_adv_ineligibility_reason": ["NELIG_ADV", "NELIG_REM"],
    },
}
