CODEMAP = {
    "source": {
        "file": "JEE Mains 2023.xlsx",
        "sheet": "Sheet1",
        "header": 0,
    },
    "constants": {
        "test_year": "2023",
        "test_name": "JEE Mains Overall",
        "max_score": 300,
    },
    # 2023 introduces dual attempts: P1A = Session 1 (January), P1B = Session 2 (April)
    "columns": {
        "application_no":           ["applicationNo", "APPNO"],
        "student_full_name":        ["CNAME", "Student Name"],
        "dob":                      ["DOB"],
        "student_gender":           ["GENDER"],
        "_pwd_raw":                 ["PWD"],
        "category":                 ["CAT"],
        "school_code":              ["SCODE_E"],
        "roll_no_s1":               ["ROLL_JAN"],
        "roll_no_s2":               ["ROLL_APR"],
        "student_state":            ["QualState", "StateName", "State"],
        "district_12":              ["QualDistrict", "districtName", "District"],
        "place_of_school":          ["PlaceofSchooling", "PlaceofSchool"],
        "jnv_name":                 ["DB JNV Name", "JNV Name"],
        "jnv_region":               ["DB JNV Region"],
        "year_of_passing_12":       ["yearOfPassing"],
        "board_12":                 ["boardName", "Board"],
        "marks_12_obtained":        ["obtainedMark"],
        "marks_12_total":           ["totalMark"],
        "marks_12_pct":             ["percentageOfMarks"],
        "appeared_for_exam":        ["PS_TOT_P1F"],
        "physics_score":            ["PS_PHY_P1F"],
        "chemistry_score":          ["PS_CHE_P1F"],
        "maths_score":              ["PS_MAT_P1F"],
        "total_score":              ["PS_TOT_P1F"],
        "physics_score_s1":         ["PS_PHY_P1A"],
        "chemistry_score_s1":       ["PS_CHE_P1A"],
        "maths_score_s1":           ["PS_MAT_P1A"],
        "total_score_s1":           ["PS_TOT_P1A"],
        "physics_score_s2":         ["PS_PHY_P1B"],
        "chemistry_score_s2":       ["PS_CHE_P1B"],
        "maths_score_s2":           ["PS_MAT_P1B"],
        "total_score_s2":           ["PS_TOT_P1B"],
        "all_india_rank":           ["AI_CRL1", "All India Rank"],
        "all_india_pwd_rank":       ["AI_CRL1PH"],
        "obc_rank":                 ["AI_OBC1"],
        "sc_rank":                  ["AI_SC1"],
        "st_rank":                  ["AI_ST1"],
        "ews_rank":                 ["AI_EWS1"],
        "jee_mains_qualified":      ["SELE", "Qualified"],
        # NELIG_ADV: True = ineligible for JEE Advanced
        "jee_adv_ineligible":       ["NELIG_ADV"],
        "jee_advanced_ineligibility_reason": ["NELIG_ADV", "NELIG_REM"],
    },
}
