CODEMAP = {
    "source": {
        "file": "JEE Mains 2021.xlsx",
        "sheet": "FullData",
        "header": 0,
    },
    "constants": {
        "test_year": "2021",
        "test_name": "JEE Mains Overall",
        "max_score": 300,
    },
    # _pwd_raw  → used internally by category normalization
    # appeared_for_exam → points to total score col to detect ABS
    "columns": {
        "application_no":           ["APPNO"],
        "student_full_name":        ["CNAME", "Student Name"],
        "dob":                      ["DOB"],
        "student_gender":           ["GENDER"],
        "_pwd_raw":                 ["PWD"],
        "category":                 ["CAT"],
        "school_code":              ["SCODE_E"],
        "roll_no_s1":               ["rollno", "ROLLNO"],
        "student_state":            ["StateName", "State"],
        "district_12":              ["districtName", "District"],
        "place_of_school":          ["PlaceofSchooling", "PlaceofSchool"],
        "jnv_name":                 ["DB JNV Name", "JNV Name"],
        "jnv_region":               ["DB JNV Region"],
        "year_of_passing_12":       ["yearOfPassing"],
        "board_12":                 ["boardName", "Board"],
        "marks_12_obtained":        ["obtainedMark"],
        "marks_12_total":           ["totalMark"],
        "marks_12_pct":             ["percentageOfMarks"],
        "appeared_for_exam":        ["PS_TOT_F"],
        "physics_score":            ["PS_PHY_F"],
        "chemistry_score":          ["PS_CHE_F"],
        "maths_score":              ["PS_MAT_F"],
        "total_score":              ["PS_TOT_F"],
        "all_india_rank":           ["All India Rank"],
        "all_india_pwd_rank":       ["AI_CRL1PH"],
        "obc_rank":                 ["AI_OBC1"],
        "sc_rank":                  ["AI_SC1"],
        "st_rank":                  ["AI_ST1"],
        "ews_rank":                 ["AI_EWS1"],
        "jee_mains_qualified":      ["Qualified"],
        # NELIG_ADV: True = ineligible for JEE Advanced
        "jee_adv_ineligible":       ["NELIG_ADV"],
        "jee_advanced_ineligibility_reason": ["NELIG_ADV", "NELIG_REM"],
    },
}
